package com.pku.portal.cache;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table CACHE.
 */
public class Cache {

    /**
     * Not-null value.
     */
    private String key;
    private String data;

    public Cache() {
    }

    public Cache(String key) {
        this.key = key;
    }

    public Cache(String key, String data) {
        this.key = key;
        this.data = data;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }
}
